x-configs: &default-configs
  # image: clickhouse/clickhouse-server:25.1
  build: .
  ulimits:
    nproc: 65535
    nofile:
      soft: 262144
      hard: 262144
  networks:
    - ch_replicated
  depends_on:
  - zookeeper
    
services:
  minio:
    restart: always
    image: quay.io/minio/minio:RELEASE.2025-03-12T18-04-18Z
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minioadmin
    # user: ${UID}:${GID}
    # user: "`id -u`:`id -g`"
    command: server /data --console-address ":9001"
    ports:
      - "9110:9000"  # API
      - "9111:9001"  # WebUI
    volumes:
      - ./minio/data:/data
      - ./minio/config:/root/.minio
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - ch_replicated

  zookeeper:
    image: 'bitnami/zookeeper:3.9.3'
    networks:
      - ch_replicated
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOOKEEPER_CLIENT_PORT=2181
    ports:
      - "2182:2181"
      - "2888:2888"
      - "3888:3888"

  clickhouse1:
    <<: *default-configs
    volumes:
      - ./configs/default_user.xml:/etc/clickhouse-server/users.d/default_user.xml
      - ./configs/z_config.xml:/etc/clickhouse-server/config.d/z_config.xml
      - ./configs/macros_ch1.xml:/etc/clickhouse-server/config.d/macros.xml
      - ./configs/clickhouse-backup.yml:/etc/clickhouse-backup/config.yml
    ports:
      - "8002:9000"
      - "9123:8123"
      
  clickhouse2:
    <<: *default-configs
    volumes:
      - ./configs/default_user.xml:/etc/clickhouse-server/users.d/default_user.xml
      - ./configs/z_config.xml:/etc/clickhouse-server/config.d/z_config.xml
      - ./configs/macros_ch2.xml:/etc/clickhouse-server/config.d/macros.xml
      - ./configs/clickhouse-backup.yml:/etc/clickhouse-backup/config.yml
    ports:
      - "8003:9000"
      - "9124:8123"
      
  clickhouse3:
    <<: *default-configs
    volumes:
      - ./configs/default_user.xml:/etc/clickhouse-server/users.d/default_user.xml
      - ./configs/z_config.xml:/etc/clickhouse-server/config.d/z_config.xml
      - ./configs/macros_ch3.xml:/etc/clickhouse-server/config.d/macros.xml
      - ./configs/clickhouse-backup.yml:/etc/clickhouse-backup/config.yml
    ports:
      - "8004:9000"
      - "9125:8123"

  clickhouse4:
    <<: *default-configs
    volumes:
      - ./configs/default_user.xml:/etc/clickhouse-server/users.d/default_user.xml
      - ./configs/z_config.xml:/etc/clickhouse-server/config.d/z_config.xml
      - ./configs/macros_ch4.xml:/etc/clickhouse-server/config.d/macros.xml
      - ./configs/clickhouse-backup.yml:/etc/clickhouse-backup/config.yml
    ports:
      - "8005:9000"
      - "9126:8123"

networks:
  ch_replicated:
    driver: bridge
  